services:
  hexapod:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        USERNAME: leonv
    container_name: hexapod_ros2
    network_mode: host
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/input:/dev/input"
    environment:
      - ROS_DOMAIN_ID=42
      - ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST
      - DISPLAY=${DISPLAY:-:0}
    volumes:
      - .:/home/ws
      - /tmp/.X11-unix:/tmp/.X11-unix
    restart: unless-stopped
    stdin_open: true
    tty: true
